version: '3.1'

services:
  n8n:
    build: .
    ports:
      - 5678:5678
    links:
      - postgres
      - nginx

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80